server:
  port: 8080
  
spring:
  application:
    name: Product Microservice
  profiles:
    active:dev
       
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: root 
    
product:
  currencies:
  - INR
  - USD
  - EUR
  
 # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    host: localhost
    port: 5432
    
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug    
    

  